Repository khalidsaadat/soen341, pull requests merged in 2022-02, with the labels that each got.

#53 Task/admin portal
  .DS_Store
  app/controllers/AccountController.php
  app/controllers/AdminController.php
  app/controllers/ProductController.php
  app/controllers/ShopController.php
  app/views/admin/index.php
  app/views/include/header.php
  app/views/product/add_product.php
  css/custom_style.css
Labels: High Priority, Pull Request

#65 filter sidebar created #50
  app/controllers/ProductController.php
  app/controllers/ShopController.php
  app/models/Product.php
  app/views/shop/index.php
Labels: Pull Request, Medium Priority

#75 Product detail page
  app/controllers/ProductController.php
  app/controllers/ShopController.php
  app/views/EXCEPTIONS/error_404.php
  app/views/shop/index.php
  app/views/shop/product_detail.php
  assets/.DS_Store
  assets/products/.DS_Store
  assets/products/images/.DS_Store
  assets/products/images/6209d7006c07f.jpg
  assets/products/images/6209d7006ec32.jpg
  assets/products/images/6209d7006edea.jpg
  assets/products/images/6209d7006f14f.jpg
  assets/products/images/6209d981f1ee2.png
  assets/products/images/6209eb89d9572.jpg
  assets/products/images/6209eb89d9d38.jpg
  assets/products/images/6209eb89da186.jpg
  assets/products/images/6209eb89da561.jpg
  assets/products/images/620aca789c0d0.png
  assets/products/images/620aca789c37a.png
  assets/products/images/620aca789c424.png
  assets/products/images/620aca789c4b6.png
  assets/products/images/620fddca1feae.png
  assets/products/images/620fddca1ff93.png
  assets/products/images/620fddca1ffd6.png
Labels: Pull Request
